MAN = pool_associate.3pool \
      pool_component_info.3pool \
      pool_component_to_elem.3pool \
      pool_conf_alloc.3pool \
      pool_dynamic_location.3pool \
      pool_error.3pool \
      pool_get_binding.3pool \
      pool_get_pool.3pool \
      pool_get_property.3pool \
      pool_resource_create.3pool \
      pool_value_alloc.3pool \
      pool_walk_components.3pool


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
