MAN = it_config_load.3iscsit \
      it_ini_create.3iscsit \
      it_portal_create.3iscsit \
      it_tgt_create.3iscsit \
      it_tpg_create.3iscsit


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
