MAN = kstat.3kstat \
      kstat_chain_update.3kstat \
      kstat_lookup.3kstat \
      kstat_open.3kstat \
      kstat_read.3kstat


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
