INCDIR=	/usr/include/netinet
INCS=	ipl.h \
	ip_auth.h \
	ip_compat.h \
	ip_fil.h \
	ip_frag.h \
	ip_htable.h \
	ip_lookup.h \
	ip_nat.h \
	ip_pool.h \
	ip_proxy.h \
	ip_state.h \
	ipf_stack.h

.include <prog.mk>
.include <inc.mk>
