INCDIR=	/usr/include/sys/ib/clients/of/sol_uverbs
INCS=	sol_uverbs.h \
	sol_uverbs2ucma.h \
	sol_uverbs_comp.h \
	sol_uverbs_event.h \
	sol_uverbs_hca.h \
	sol_uverbs_qp.h

.include <prog.mk>
.include <inc.mk>
