MAN=   accept.2 bind.2 connect.2 getpeername.2 getsockname.2 getsockopt.2 \
       listen.2 recv.2 send.2 shutdown.2 socket.2 socketpair.2 uname.2 \
       CMSG_DATA.3 alloca.3 err.3 fts.3 inet.3 malloc.3 readdir.3 sockatmark.3 \
       strtonum.3 posix_memalign.3 setmode.3 valloc.3 unvis.3 vis.3
# no source yet.
NOOBJ=

# lib.mk doesn't allow empty LIB, so use prog.mk to install just the manpages
# until we actually build code from here
.include <prog.mk>
