MAN = bootfs.7fs \
      ctfs.7fs \
      dcfs.7fs \
      dev.7fs \
      devfs.7fs \
      fd.7fs \
      hsfs.7fs \
      lofs.7fs \
      objfs.7fs \
      pcfs.7fs \
      sharefs.7fs \
      smbfs.7fs \
      tmpfs.7fs \
      udfs.7fs \
      ufs.7fs


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
