MAN = cpc.3cpc \
      cpc_access.3cpc \
      cpc_bind_curlwp.3cpc \
      cpc_bind_event.3cpc \
      cpc_buf_create.3cpc \
      cpc_count_usr_events.3cpc \
      cpc_enable.3cpc \
      cpc_event.3cpc \
      cpc_event_diff.3cpc \
      cpc_getcpuver.3cpc \
      cpc_npic.3cpc \
      cpc_open.3cpc \
      cpc_pctx_bind_event.3cpc \
      cpc_set_create.3cpc \
      cpc_seterrfn.3cpc \
      cpc_seterrhndlr.3cpc \
      cpc_shared_open.3cpc \
      cpc_strtoevent.3cpc \
      cpc_version.3cpc \
      generic_events.3cpc \
      pctx_capture.3cpc \
      pctx_set_events.3cpc


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
