MAN = pam.3pam \
      pam_acct_mgmt.3pam \
      pam_authenticate.3pam \
      pam_chauthtok.3pam \
      pam_get_user.3pam \
      pam_getenv.3pam \
      pam_getenvlist.3pam \
      pam_open_session.3pam \
      pam_putenv.3pam \
      pam_set_data.3pam \
      pam_set_item.3pam \
      pam_setcred.3pam \
      pam_sm.3pam \
      pam_sm_acct_mgmt.3pam \
      pam_sm_authenticate.3pam \
      pam_sm_chauthtok.3pam \
      pam_sm_open_session.3pam \
      pam_sm_setcred.3pam \
      pam_start.3pam \
      pam_strerror.3pam


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
