MAN = scf_entry_create.3scf \
      scf_error.3scf \
      scf_handle_create.3scf \
      scf_handle_decode_fmri.3scf \
      scf_instance_create.3scf \
      scf_iter_create.3scf \
      scf_limit.3scf \
      scf_pg_create.3scf \
      scf_property_create.3scf \
      scf_scope_create.3scf \
      scf_service_create.3scf \
      scf_simple_prop_get.3scf \
      scf_simple_walk_instances.3scf \
      scf_snaplevel_create.3scf \
      scf_snapshot_create.3scf \
      scf_tmpl_pg_create.3scf \
      scf_tmpl_pg_name.3scf \
      scf_tmpl_prop_create.3scf \
      scf_tmpl_prop_name.3scf \
      scf_tmpl_validate_fmri.3scf \
      scf_transaction_create.3scf \
      scf_value_create.3scf \
      smf_enable_instance.3scf


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
