INCDIR=	/usr/platform/include/sys
INCS=	acpidev.h	\
	amd_iommu.h	\
	asm_misc.h	\
	clock.h		\
	cram.h		\
	ddi_subrdefs.h	\
	debug_info.h 	\
	fastboot.h	\
	mach_mmu.h	\
	machclock.h	\
	machcpuvar.h	\
	machparam.h	\
	machprivregs.h	\
	machsystm.h	\
	machthread.h	\
	memnode.h	\
	pc_mmu.h	\
	psm.h		\
	psm_defs.h	\
	psm_modctl.h	\
	psm_types.h	\
	rm_platter.h	\
	sbd_ioctl.h	\
	smp_impldefs.h	\
	vm_machparam.h	\
	x_call.h	\
	xc_levels.h	\
	xsvc.h

.include <unleashed.mk>
.include <prog.mk>
.include <inc.mk>

.include <${SRCTOP}/cfgparam.mk>
