MAN = avl_add.3avl \
      avl_create.3avl \
      avl_destroy.3avl \
      avl_destroy_nodes.3avl \
      avl_find.3avl \
      avl_first.3avl \
      avl_insert.3avl \
      avl_is_empty.3avl \
      avl_nearest.3avl \
      avl_numnodes.3avl \
      avl_swap.3avl


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
