SUBDIR = datafilt \
	 httpfilt \
	 pfp \
	 rds \
	 sctp

# NOTE: The sdp module is not build because it depends on what used to be a
# closed binary-only kernel module drv/sdpib.  Someone should figure out
# what to do with sdp in general.

.include <bsd.subdir.mk>
