MAN = endhostent.3xnet \
      endnetent.3xnet \
      endprotoent.3xnet \
      endservent.3xnet \
      freeaddrinfo.3xnet \
      gai_strerror.3xnet \
      gethostname.3xnet \
      getnameinfo.3xnet \
      htonl.3xnet \
      if_nametoindex.3xnet \
      inet_addr.3xnet \
      inet_ntop.3xnet


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
