MAN = dlcosmk.7ipp \
      dscpmk.7ipp \
      flowacct.7ipp \
      ipgpc.7ipp \
      ipqos.7ipp \
      tokenmt.7ipp \
      tswtclmt.7ipp

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
