INCDIR=	/usr/include/sys/ib/ibtl
INCS=	ibci.h \
	ibti.h \
	ibti_cm.h \
	ibti_common.h \
	ibtl_ci_types.h \
	ibtl_status.h \
	ibtl_types.h \
	ibvti.h

SUBDIR=	impl

.include <prog.mk>
.include <inc.mk>
