SUBDIR = autofs \
	 bootfs \
	 ctfs \
	 dcfs \
	 dev \
	 devfs \
	 doorfs \
	 fdfs \
	 fifofs \
	 hsfs \
	 lofs \
	 mntfs \
	 namefs \
	 nfs \
	 objfs \
	 pcfs \
	 portfs \
	 sockfs \
	 specfs \
	 tmpfs \
	 udfs \
	 ufs \
	 zfs

.include <bsd.subdir.mk>
