INCDIR=	/usr/include/iso
INCS=	ctype_iso.h	\
	limits_iso.h	\
	locale_iso.h	\
	math_c99.h	\
	math_iso.h	\
	setjmp_iso.h  	\
	signal_iso.h	\
	stdarg_c99.h	\
	stdarg_iso.h	\
	stddef_iso.h	\
	stdio_c99.h	\
	stdio_iso.h	\
	stdlib_c99.h	\
	stdlib_c11.h	\
	stdlib_iso.h	\
	string_iso.h	\
	time_iso.h	\
	wchar_c99.h	\
	wchar_iso.h	\
	wctype_iso.h

SYMLINKS=	../assert.h /usr/include/iso/assert_iso.h \
		../errno.h /usr/include/iso/errno_iso.h \
		../float.h /usr/include/iso/float_iso.h \
		../iso646.h /usr/include/iso/iso646_iso.h

.include <prog.mk>
.include <inc.mk>
