MAN = Kstat.3perl \
      Lgrp.3perl \
      Project.3perl \
      Task.3perl

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
