MAN = stmfAddToHostGroup.3stmf \
      stmfAddToTargetGroup.3stmf \
      stmfAddViewEntry.3stmf \
      stmfClearProviderData.3stmf \
      stmfCreateHostGroup.3stmf \
      stmfCreateLu.3stmf \
      stmfCreateLuResource.3stmf \
      stmfCreateTargetGroup.3stmf \
      stmfDeleteHostGroup.3stmf \
      stmfDeleteLu.3stmf \
      stmfDeleteTargetGroup.3stmf \
      stmfDevidFromIscsiName.3stmf \
      stmfDevidFromWwn.3stmf \
      stmfFreeLuResource.3stmf \
      stmfFreeMemory.3stmf \
      stmfGetHostGroupList.3stmf \
      stmfGetHostGroupMembers.3stmf \
      stmfGetLogicalUnitList.3stmf \
      stmfGetLogicalUnitProperties.3stmf \
      stmfGetLuResource.3stmf \
      stmfGetPersistMethod.3stmf \
      stmfGetProviderData.3stmf \
      stmfGetProviderDataProt.3stmf \
      stmfGetState.3stmf \
      stmfGetTargetGroupList.3stmf \
      stmfGetTargetGroupMembers.3stmf \
      stmfGetTargetList.3stmf \
      stmfGetTargetProperties.3stmf \
      stmfGetViewEntryList.3stmf \
      stmfModifyLu.3stmf \
      stmfOfflineLogicalUnit.3stmf \
      stmfOfflineTarget.3stmf \
      stmfOnlineLogicalUnit.3stmf \
      stmfOnlineTarget.3stmf \
      stmfRemoveFromHostGroup.3stmf \
      stmfRemoveFromTargetGroup.3stmf \
      stmfRemoveViewEntry.3stmf \
      stmfSetLuProp.3stmf \
      stmfSetPersistMethod.3stmf \
      stmfSetProviderData.3stmf \
      stmfSetProviderDataProt.3stmf


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
