MAN = di_binding_name.3devinfo \
      di_child_node.3devinfo \
      di_devfs_path.3devinfo \
      di_devlink_dup.3devinfo \
      di_devlink_init.3devinfo \
      di_devlink_path.3devinfo \
      di_devlink_walk.3devinfo \
      di_init.3devinfo \
      di_link_next_by_node.3devinfo \
      di_link_spectype.3devinfo \
      di_lnode_name.3devinfo \
      di_lnode_next.3devinfo \
      di_minor_devt.3devinfo \
      di_minor_next.3devinfo \
      di_node_private_set.3devinfo \
      di_path_bus_addr.3devinfo \
      di_path_client_next_path.3devinfo \
      di_path_prop_bytes.3devinfo \
      di_path_prop_lookup_bytes.3devinfo \
      di_path_prop_next.3devinfo \
      di_prom_init.3devinfo \
      di_prom_prop_data.3devinfo \
      di_prom_prop_lookup_bytes.3devinfo \
      di_prop_bytes.3devinfo \
      di_prop_lookup_bytes.3devinfo \
      di_prop_next.3devinfo \
      di_walk_link.3devinfo \
      di_walk_lnode.3devinfo \
      di_walk_minor.3devinfo \
      di_walk_node.3devinfo


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
