MAN = cpl_complete_word.3tecla \
      ef_expand_file.3tecla \
      gl_get_line.3tecla \
      gl_io_mode.3tecla \
      libtecla_version.3tecla \
      pca_lookup_file.3tecla


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
