MAN = vatan2_.3mvec \
      vatan_.3mvec \
      vcos_.3mvec \
      vcospi_.3mvec \
      vexp_.3mvec \
      vhypot_.3mvec \
      vlog_.3mvec \
      vpow_.3mvec \
      vrhypot_.3mvec \
      vrsqrt_.3mvec \
      vsin_.3mvec \
      vsincos_.3mvec \
      vsincospi_.3mvec \
      vsinpi_.3mvec \
      vsqrt_.3mvec \
      vz_abs_.3mvec \
      vz_exp_.3mvec \
      vz_log_.3mvec \
      vz_pow_.3mvec

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
