INCDIR=	/usr/include/sys/scsi/impl
INCS=	commands.h \
	inquiry.h \
	mode.h \
	scsi_reset_notify.h \
	scsi_sas.h \
	sense.h \
	services.h \
	smp_transport.h \
	spc3_types.h \
	status.h \
	transport.h \
	types.h \
	uscsi.h \
	usmp.h

.include <prog.mk>
.include <inc.mk>
