INCDIR=	/usr/include/vm
INCS=	anon.h \
	as.h \
	faultcode.h \
	hat.h \
	kpm.h \
	object.h \
	page.h \
	pvn.h \
	rm.h \
	seg.h \
	seg_dev.h \
	seg_enum.h \
	seg_kmem.h \
	seg_kp.h \
	seg_kpm.h \
	seg_map.h \
	seg_spt.h \
	seg_vn.h \
	vpage.h \
	vpm.h

.include <prog.mk>
.include <inc.mk>
