MAN = td_init.3c_db \
      td_log.3c_db \
      td_sync_get_info.3c_db \
      td_ta_enable_stats.3c_db \
      td_ta_event_addr.3c_db \
      td_ta_get_nthreads.3c_db \
      td_ta_map_addr2sync.3c_db \
      td_ta_map_id2thr.3c_db \
      td_ta_new.3c_db \
      td_ta_setconcurrency.3c_db \
      td_ta_sync_iter.3c_db \
      td_thr_dbsuspend.3c_db \
      td_thr_get_info.3c_db \
      td_thr_getgregs.3c_db \
      td_thr_lockowner.3c_db \
      td_thr_setprio.3c_db \
      td_thr_setsigpending.3c_db \
      td_thr_sleepinfo.3c_db \
      td_thr_tsd.3c_db \
      td_thr_validate.3c_db


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
