INCDIR=	/usr/include/sys/scsi/generic
INCS=	commands.h \
	dad_mode.h \
	inquiry.h \
	message.h \
	mode.h \
	persist.h \
	sense.h \
	sff_frames.h \
	smp_frames.h \
	status.h

.include <prog.mk>
.include <inc.mk>
