.\" Copyright 2014 Garrett D'Amore <garrett@damore.org>
.\" Copyright 1989 AT&T  Copyright (c) 2001, Sun Microsystems, Inc.  All Rights Reserved  Portions Copyright (c) 1992, X/Open Company Limited  All Rights Reserved
.\" Sun Microsystems, Inc. gratefully acknowledges The Open Group for permission to reproduce portions of its copyrighted documentation. Original documentation from The Open Group can be obtained online at
.\" http://www.opengroup.org/bookstore/.
.\" The Institute of Electrical and Electronics Engineers and The Open Group, have given us permission to reprint portions of their documentation. In the following statement, the phrase "this text" refers to portions of the system documentation. Portions of this text are reprinted and reproduced in electronic form in the Sun OS Reference Manual, from IEEE Std 1003.1, 2004 Edition, Standard for Information Technology -- Portable Operating System Interface (POSIX), The Open Group Base Specifications Issue 6, Copyright (C) 2001-2004 by the Institute of Electrical and Electronics Engineers, Inc and The Open Group. In the event of any discrepancy between these versions and the original IEEE and The Open Group Standard, the original IEEE and The Open Group Standard is the referee document. The original Standard can be obtained online at http://www.opengroup.org/unix/online.html.
.\"  This notice shall appear on any product containing this material.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.Dd Aug 21, 2014
.Dt BASENAME 1
.Os
.Sh NAME
.Nm basename ,
.Nm dirname
.Nd deliver portions of path names
.Sh SYNOPSIS
.Nm basename
.Ar string
.Op Ar suffix
.Nm dirname
.Ar string
.Sh DESCRIPTION
The
.Nm basename
utility deletes any prefix ending in
.Li /
and the
.Ar suffix
.Pq if present in Ar string
from
.Ar string ,
and prints the
result on the standard output. It is normally used inside substitution marks
(\fB`\|`\fR) within shell procedures.
.Lp
The
.Ar suffix
is a string with no special significance attached to  any of
the characters it contains.
.Lp
The
.Nm dirname
utility delivers all but the last level of the path name in
.Ar string .
.Sh ENVIRONMENT
See
.Xr environ 5
for descriptions of the following environment variables
that affect  the execution of
.Nm basename
and
.Nm dirname :
.Ev LANG ,
.Ev LC_ALL ,
.Ev LC_CTYPE ,
.Ev LC_MESSAGES ,
and
.Ev NLSPATH .
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Ss Example 1 Setting environment variables
The following example, invoked with the argument
.Pa /home/sms/personal/mail
sets the environment variable
.Ev NAME
to the file named
.Pa mail
and the
environment variable
.Ev MYMAILPATH
to the string
.Pa /home/sms/personal :
.Bd -literal
example% NAME=`basename \|$HOME/personal/mail`
example% MYMAILPATH=`dirname \|$HOME/personal/mail`
.Ed
.Ss Example 2 Compiling a file and moving the output
This shell procedure, invoked with the argument
.Pa /usr/src/bin/cat.c ,
compiles the named file and moves the output to
.Pa cat
in the current directory:
.Bd -literal
example% cc $1
example% mv a.out `basename $1 .c`
.Ed
.Sh INTERFACE STABILITY
.Sy Standard .
.Sh SEE ALSO
.Xr expr 1 ,
.Xr basename 3C ,
.Xr environ 5 ,
.Xr standards 5
.Sh STANDARDS
These utilities conform to the following standards.  See
.Xr standards 5 .
.Lp
.Bl -bullet -compact
.It
.St -xpg4
.It
.St -xpg4.2
.It
.St -susv2
.It
.St -susv2
.It
.St -p1003.1-2008
.El
