MAN = sasl_authorize_t.3sasl \
      sasl_auxprop.3sasl \
      sasl_auxprop_add_plugin.3sasl \
      sasl_auxprop_getctx.3sasl \
      sasl_auxprop_request.3sasl \
      sasl_canon_user_t.3sasl \
      sasl_canonuser_add_plugin.3sasl \
      sasl_chalprompt_t.3sasl \
      sasl_checkapop.3sasl \
      sasl_checkpass.3sasl \
      sasl_client_add_plugin.3sasl \
      sasl_client_init.3sasl \
      sasl_client_new.3sasl \
      sasl_client_plug_init_t.3sasl \
      sasl_client_start.3sasl \
      sasl_client_step.3sasl \
      sasl_decode.3sasl \
      sasl_decode64.3sasl \
      sasl_dispose.3sasl \
      sasl_done.3sasl \
      sasl_encode.3sasl \
      sasl_encode64.3sasl \
      sasl_erasebuffer.3sasl \
      sasl_errdetail.3sasl \
      sasl_errors.3sasl \
      sasl_errstring.3sasl \
      sasl_getcallback_t.3sasl \
      sasl_getopt_t.3sasl \
      sasl_getpath_t.3sasl \
      sasl_getprop.3sasl \
      sasl_getrealm_t.3sasl \
      sasl_getsecret_t.3sasl \
      sasl_getsimple_t.3sasl \
      sasl_global_listmech.3sasl \
      sasl_idle.3sasl \
      sasl_listmech.3sasl \
      sasl_log_t.3sasl \
      sasl_server_add_plugin.3sasl \
      sasl_server_init.3sasl \
      sasl_server_new.3sasl \
      sasl_server_plug_init_t.3sasl \
      sasl_server_start.3sasl \
      sasl_server_step.3sasl \
      sasl_server_userdb_checkpass_t.3sasl \
      sasl_server_userdb_setpass_t.3sasl \
      sasl_set_alloc.3sasl \
      sasl_set_mutex.3sasl \
      sasl_seterror.3sasl \
      sasl_setpass.3sasl \
      sasl_setprop.3sasl \
      sasl_utf8verify.3sasl \
      sasl_verifyfile_t.3sasl \
      sasl_version.3sasl


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
