INCDIR=	/usr/include/sys/sysevent
INCS=	ap_driver.h     \
	dev.h		\
	domain.h        \
	dr.h            \
	env.h           \
	eventdefs.h	\
	ipmp.h		\
	pwrctl.h	\
	vrrp.h

.include <prog.mk>
.include <inc.mk>
