MAN = FCOE_CreatePort.3fcoe \
      FCOE_DeletePort.3fcoe \
      FCOE_GetPortList.3fcoe

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
