MAN = media_findname.3volmgt \
      media_getattr.3volmgt \
      media_getid.3volmgt \
      volmgt_acquire.3volmgt \
      volmgt_check.3volmgt \
      volmgt_feature_enabled.3volmgt \
      volmgt_inuse.3volmgt \
      volmgt_ownspath.3volmgt \
      volmgt_release.3volmgt \
      volmgt_root.3volmgt \
      volmgt_running.3volmgt \
      volmgt_symname.3volmgt


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
