MAN = ea_error.3exacct \
      ea_open.3exacct \
      ea_pack_object.3exacct \
      ea_set_item.3exacct


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
