MAN = Intro.3 \
      byteorder.3 \
      endian.3 \
      hosts_access.3 \
      memset_s.3 \
      set_constraint_handler_s.3


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
