MAN = getauthattr.3secdb \
      getexecattr.3secdb \
      getprofattr.3secdb \
      getuserattr.3secdb \
      kva_match.3secdb


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
