MAN = NOTE.3ext \
      SUNW_C_GetMechSession.3ext \
      auto_ef.3ext \
      crypt.3ext \
      ecb_crypt.3ext \
      efi_alloc_and_init.3ext \
      ld_support.3ext \
      md4.3ext \
      md5.3ext \
      read_vtoc.3ext \
      rtld_audit.3ext \
      rtld_db.3ext \
      sendfile.3ext \
      sendfilev.3ext \
      sha1.3ext \
      sha2.3ext \
      stdarg.3ext \
      varargs.3ext


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
