#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
# Copyright 2014 Garrett D'Amore <garrett@damore.org>
#

file path=usr/share/man/man4/Intro.4
file path=usr/share/man/man4/auth_attr.4
file path=usr/share/man/man4/contract.4
file path=usr/share/man/man4/core.4
file path=usr/share/man/man4/crypt.conf.4
file path=usr/share/man/man4/crypto_certs.4
file path=usr/share/man/man4/ctf.4
file path=usr/share/man/man4/d_passwd.4
file path=usr/share/man/man4/dacf.conf.4
file path=usr/share/man/man4/default_fs.4
file path=usr/share/man/man4/defaultrouter.4
file path=usr/share/man/man4/device_contract.4
file path=usr/share/man/man4/devices.4
file path=usr/share/man/man4/dfstab.4
file path=usr/share/man/man4/dhcp_inittab.4
file path=usr/share/man/man4/dialups.4
file path=usr/share/man/man4/ethers.4
file path=usr/share/man/man4/exec_attr.4
file path=usr/share/man/man4/format.dat.4
file path=usr/share/man/man4/fspec.4
file path=usr/share/man/man4/fstypes.4
file path=usr/share/man/man4/ftpusers.4
file path=usr/share/man/man4/fx_dptbl.4
file path=usr/share/man/man4/group.4
file path=usr/share/man/man4/hosts.4
file path=usr/share/man/man4/inet_type.4
file path=usr/share/man/man4/inetd.conf.4
file path=usr/share/man/man4/init.4
file path=usr/share/man/man4/init.d.4
file path=usr/share/man/man4/inittab.4
file path=usr/share/man/man4/ipaddrsel.conf.4
file path=usr/share/man/man4/ipnodes.4
file path=usr/share/man/man4/issue.4
file path=usr/share/man/man4/logadm.conf.4
file path=usr/share/man/man4/logindevperm.4
file path=usr/share/man/man4/loginlog.4
file path=usr/share/man/man4/mnttab.4
file path=usr/share/man/man4/ndpd.conf.4
file path=usr/share/man/man4/netconfig.4
file path=usr/share/man/man4/netgroup.4
file path=usr/share/man/man4/netid.4
file path=usr/share/man/man4/netmasks.4
file path=usr/share/man/man4/networks.4
file path=usr/share/man/man4/nodename.4
file path=usr/share/man/man4/nologin.4
file path=usr/share/man/man4/notrouter.4
file path=usr/share/man/man4/nscd.conf.4
file path=usr/share/man/man4/nsswitch.conf.4
file path=usr/share/man/man4/packingrules.4
file path=usr/share/man/man4/pam.conf.4
file path=usr/share/man/man4/passwd.4
file path=usr/share/man/man4/phones.4
file path=usr/share/man/man4/policy.conf.4
file path=usr/share/man/man4/prof_attr.4
file path=usr/share/man/man4/profile.4
file path=usr/share/man/man4/project.4
file path=usr/share/man/man4/protocols.4
file path=usr/share/man/man4/queuedefs.4
file path=usr/share/man/man4/rcmscript.4
file path=usr/share/man/man4/remote.4
file path=usr/share/man/man4/rpc.4
file path=usr/share/man/man4/rt_dptbl.4
file path=usr/share/man/man4/service_bundle.4
file path=usr/share/man/man4/service_provider.conf.4
file path=usr/share/man/man4/services.4
file path=usr/share/man/man4/shadow.4
file path=usr/share/man/man4/sharetab.4
file path=usr/share/man/man4/shells.4
file path=usr/share/man/man4/sulog.4
file path=usr/share/man/man4/syslog.conf.4
file path=usr/share/man/man4/term.4
file path=usr/share/man/man4/terminfo.4
file path=usr/share/man/man4/timezone.4
file path=usr/share/man/man4/ttydefs.4
file path=usr/share/man/man4/ttysrch.4
file path=usr/share/man/man4/ufsdump.4
file path=usr/share/man/man4/user_attr.4
file path=usr/share/man/man4/utmp.4
file path=usr/share/man/man4/utmpx.4
file path=usr/share/man/man4/vfstab.4
