#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
# Copyright 2013, OmniTI Computer Consulting, Inc.
# Copyright 2017 Peter Tribble
# Copyright 2018, Joyent, Inc.
#

file path=usr/share/man/man2/Intro.2
file path=usr/share/man/man2/__sparc_utrap_install.2
file path=usr/share/man/man2/_lwp_cond_signal.2
file path=usr/share/man/man2/_lwp_cond_wait.2
file path=usr/share/man/man2/_lwp_info.2
file path=usr/share/man/man2/_lwp_kill.2
file path=usr/share/man/man2/_lwp_mutex_lock.2
file path=usr/share/man/man2/_lwp_self.2
file path=usr/share/man/man2/_lwp_sema_wait.2
file path=usr/share/man/man2/_lwp_suspend.2
file path=usr/share/man/man2/accept.2
file path=usr/share/man/man2/access.2
file path=usr/share/man/man2/acct.2
file path=usr/share/man/man2/acl.2
file path=usr/share/man/man2/adjtime.2
file path=usr/share/man/man2/alarm.2
file path=usr/share/man/man2/bind.2
file path=usr/share/man/man2/brk.2
file path=usr/share/man/man2/chdir.2
file path=usr/share/man/man2/chmod.2
file path=usr/share/man/man2/chown.2
file path=usr/share/man/man2/chroot.2
file path=usr/share/man/man2/close.2
file path=usr/share/man/man2/connect.2
file path=usr/share/man/man2/creat.2
file path=usr/share/man/man2/dup.2
file path=usr/share/man/man2/exec.2
file path=usr/share/man/man2/exit.2
file path=usr/share/man/man2/fcntl.2
file path=usr/share/man/man2/fork.2
file path=usr/share/man/man2/fpathconf.2
file path=usr/share/man/man2/getacct.2
file path=usr/share/man/man2/getcontext.2
file path=usr/share/man/man2/getdents.2
file path=usr/share/man/man2/getgroups.2
file path=usr/share/man/man2/getisax.2
file path=usr/share/man/man2/getitimer.2
file path=usr/share/man/man2/getmsg.2
file path=usr/share/man/man2/getpeername.2
file path=usr/share/man/man2/getpflags.2
file path=usr/share/man/man2/getpid.2
file path=usr/share/man/man2/getppriv.2
file path=usr/share/man/man2/getrandom.2
file path=usr/share/man/man2/getrlimit.2
file path=usr/share/man/man2/getsid.2
file path=usr/share/man/man2/getsockname.2
file path=usr/share/man/man2/getsockopt.2
file path=usr/share/man/man2/getuid.2
file path=usr/share/man/man2/getustack.2
file path=usr/share/man/man2/ioctl.2
file path=usr/share/man/man2/issetugid.2
file path=usr/share/man/man2/kill.2
file path=usr/share/man/man2/link.2
file path=usr/share/man/man2/listen.2
file path=usr/share/man/man2/llseek.2
file path=usr/share/man/man2/lseek.2
file path=usr/share/man/man2/memcntl.2
file path=usr/share/man/man2/meminfo.2
file path=usr/share/man/man2/mincore.2
file path=usr/share/man/man2/mkdir.2
file path=usr/share/man/man2/mknod.2
file path=usr/share/man/man2/mmap.2
file path=usr/share/man/man2/mmapobj.2
file path=usr/share/man/man2/mount.2
file path=usr/share/man/man2/mprotect.2
file path=usr/share/man/man2/msgctl.2
file path=usr/share/man/man2/msgget.2
file path=usr/share/man/man2/msgids.2
file path=usr/share/man/man2/msgrcv.2
file path=usr/share/man/man2/msgsnap.2
file path=usr/share/man/man2/msgsnd.2
file path=usr/share/man/man2/munmap.2
file path=usr/share/man/man2/nice.2
file path=usr/share/man/man2/ntp_adjtime.2
file path=usr/share/man/man2/ntp_gettime.2
file path=usr/share/man/man2/open.2
file path=usr/share/man/man2/p_online.2
file path=usr/share/man/man2/pause.2
file path=usr/share/man/man2/pcsample.2
file path=usr/share/man/man2/pipe.2
file path=usr/share/man/man2/poll.2
file path=usr/share/man/man2/priocntl.2
file path=usr/share/man/man2/priocntlset.2
file path=usr/share/man/man2/processor_bind.2
file path=usr/share/man/man2/processor_info.2
file path=usr/share/man/man2/profil.2
file path=usr/share/man/man2/pset_bind.2
file path=usr/share/man/man2/pset_create.2
file path=usr/share/man/man2/pset_info.2
file path=usr/share/man/man2/pset_list.2
file path=usr/share/man/man2/pset_setattr.2
file path=usr/share/man/man2/putmsg.2
file path=usr/share/man/man2/read.2
file path=usr/share/man/man2/readlink.2
file path=usr/share/man/man2/recv.2
file path=usr/share/man/man2/rename.2
file path=usr/share/man/man2/resolvepath.2
file path=usr/share/man/man2/rmdir.2
file path=usr/share/man/man2/semctl.2
file path=usr/share/man/man2/semget.2
file path=usr/share/man/man2/semids.2
file path=usr/share/man/man2/semop.2
file path=usr/share/man/man2/send.2
file path=usr/share/man/man2/setpgid.2
file path=usr/share/man/man2/setpgrp.2
file path=usr/share/man/man2/setrctl.2
file path=usr/share/man/man2/setregid.2
file path=usr/share/man/man2/setreuid.2
file path=usr/share/man/man2/setsid.2
file path=usr/share/man/man2/settaskid.2
file path=usr/share/man/man2/setuid.2
file path=usr/share/man/man2/shmctl.2
file path=usr/share/man/man2/shmget.2
file path=usr/share/man/man2/shmids.2
file path=usr/share/man/man2/shmop.2
file path=usr/share/man/man2/shutdown.2
file path=usr/share/man/man2/sigaction.2
file path=usr/share/man/man2/sigaltstack.2
file path=usr/share/man/man2/sigpending.2
file path=usr/share/man/man2/sigprocmask.2
file path=usr/share/man/man2/sigsend.2
file path=usr/share/man/man2/sigsuspend.2
file path=usr/share/man/man2/sigwait.2
file path=usr/share/man/man2/socket.2
file path=usr/share/man/man2/socketpair.2
file path=usr/share/man/man2/stat.2
file path=usr/share/man/man2/statvfs.2
file path=usr/share/man/man2/stime.2
file path=usr/share/man/man2/swapctl.2
file path=usr/share/man/man2/symlink.2
file path=usr/share/man/man2/sync.2
file path=usr/share/man/man2/sysfs.2
file path=usr/share/man/man2/sysinfo.2
file path=usr/share/man/man2/time.2
file path=usr/share/man/man2/times.2
file path=usr/share/man/man2/uadmin.2
file path=usr/share/man/man2/ulimit.2
file path=usr/share/man/man2/umask.2
file path=usr/share/man/man2/umount.2
file path=usr/share/man/man2/uname.2
file path=usr/share/man/man2/unlink.2
file path=usr/share/man/man2/ustat.2
file path=usr/share/man/man2/utime.2
file path=usr/share/man/man2/utimes.2
file path=usr/share/man/man2/uucopy.2
file path=usr/share/man/man2/vfork.2
file path=usr/share/man/man2/vhangup.2
file path=usr/share/man/man2/waitid.2
file path=usr/share/man/man2/write.2
file path=usr/share/man/man2/yield.2
