#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3ext/NOTE.3ext
file path=usr/share/man/man3ext/SUNW_C_GetMechSession.3ext
file path=usr/share/man/man3ext/auto_ef.3ext
file path=usr/share/man/man3ext/crypt.3ext
file path=usr/share/man/man3ext/ecb_crypt.3ext
file path=usr/share/man/man3ext/efi_alloc_and_init.3ext
file path=usr/share/man/man3ext/ld_support.3ext
file path=usr/share/man/man3ext/md4.3ext
file path=usr/share/man/man3ext/md5.3ext
file path=usr/share/man/man3ext/read_vtoc.3ext
file path=usr/share/man/man3ext/rtld_audit.3ext
file path=usr/share/man/man3ext/rtld_db.3ext
file path=usr/share/man/man3ext/sendfile.3ext
file path=usr/share/man/man3ext/sendfilev.3ext
file path=usr/share/man/man3ext/sha1.3ext
file path=usr/share/man/man3ext/sha2.3ext
file path=usr/share/man/man3ext/stdarg.3ext
file path=usr/share/man/man3ext/varargs.3ext
