#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3xnet/endhostent.3xnet
file path=usr/share/man/man3xnet/endnetent.3xnet
file path=usr/share/man/man3xnet/endprotoent.3xnet
file path=usr/share/man/man3xnet/endservent.3xnet
file path=usr/share/man/man3xnet/freeaddrinfo.3xnet
file path=usr/share/man/man3xnet/gai_strerror.3xnet
file path=usr/share/man/man3xnet/gethostname.3xnet
file path=usr/share/man/man3xnet/getnameinfo.3xnet
file path=usr/share/man/man3xnet/htonl.3xnet
file path=usr/share/man/man3xnet/if_nametoindex.3xnet
file path=usr/share/man/man3xnet/inet_addr.3xnet
file path=usr/share/man/man3xnet/inet_ntop.3xnet
