#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2018 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3/CMSG_DATA.3
file path=usr/share/man/man3/Intro.3
file path=usr/share/man/man3/alloca.3
file path=usr/share/man/man3/byteorder.3
file path=usr/share/man/man3/endian.3
file path=usr/share/man/man3/err.3
file path=usr/share/man/man3/fts.3
file path=usr/share/man/man3/inet.3
file path=usr/share/man/man3/malloc.3
file path=usr/share/man/man3/memset_s.3
file path=usr/share/man/man3/posix_memalign.3
file path=usr/share/man/man3/readdir.3
file path=usr/share/man/man3/set_constraint_handler_s.3
file path=usr/share/man/man3/setmode.3
file path=usr/share/man/man3/sockatmark.3
file path=usr/share/man/man3/strtonum.3
file path=usr/share/man/man3/unvis.3
file path=usr/share/man/man3/valloc.3
file path=usr/share/man/man3/vis.3
