#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2018 Nexenta Systems, Inc.
# Copyright 2013, OmniTI Computer Consulting, Inc.
#

file path=usr/share/man/man3socket/ethers.3socket
file path=usr/share/man/man3socket/getaddrinfo.3socket
file path=usr/share/man/man3socket/getifaddrs.3socket
file path=usr/share/man/man3socket/getipnodebyname.3socket
file path=usr/share/man/man3socket/getnetbyname.3socket
file path=usr/share/man/man3socket/getprotobyname.3socket
file path=usr/share/man/man3socket/getservbyname.3socket
file path=usr/share/man/man3socket/getsourcefilter.3socket
file path=usr/share/man/man3socket/icmp6_filter.3socket
file path=usr/share/man/man3socket/if_nametoindex.3socket
file path=usr/share/man/man3socket/inet6_opt.3socket
file path=usr/share/man/man3socket/inet6_rth.3socket
file path=usr/share/man/man3socket/sctp_bindx.3socket
file path=usr/share/man/man3socket/sctp_getladdrs.3socket
file path=usr/share/man/man3socket/sctp_getpaddrs.3socket
file path=usr/share/man/man3socket/sctp_opt_info.3socket
file path=usr/share/man/man3socket/sctp_peeloff.3socket
file path=usr/share/man/man3socket/sctp_recvmsg.3socket
file path=usr/share/man/man3socket/sctp_send.3socket
file path=usr/share/man/man3socket/sctp_sendmsg.3socket
file path=usr/share/man/man3socket/sockaddr.3socket
file path=usr/share/man/man3socket/spray.3socket
