MAN = elf.3elf \
      elf32_checksum.3elf \
      elf32_fsize.3elf \
      elf32_getehdr.3elf \
      elf32_getphdr.3elf \
      elf32_getshdr.3elf \
      elf32_xlatetof.3elf \
      elf_begin.3elf \
      elf_cntl.3elf \
      elf_errmsg.3elf \
      elf_fill.3elf \
      elf_flagdata.3elf \
      elf_getarhdr.3elf \
      elf_getarsym.3elf \
      elf_getbase.3elf \
      elf_getdata.3elf \
      elf_getident.3elf \
      elf_getscn.3elf \
      elf_hash.3elf \
      elf_kind.3elf \
      elf_rawfile.3elf \
      elf_strptr.3elf \
      elf_update.3elf \
      elf_version.3elf \
      gelf.3elf \
      nlist.3elf


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
