MAN = rsm_create_localmemory_handle.3rsm \
      rsm_get_controller.3rsm \
      rsm_get_interconnect_topology.3rsm \
      rsm_get_segmentid_range.3rsm \
      rsm_intr_signal_post.3rsm \
      rsm_intr_signal_wait_pollfd.3rsm \
      rsm_memseg_export_create.3rsm \
      rsm_memseg_export_publish.3rsm \
      rsm_memseg_get_pollfd.3rsm \
      rsm_memseg_import_connect.3rsm \
      rsm_memseg_import_get.3rsm \
      rsm_memseg_import_init_barrier.3rsm \
      rsm_memseg_import_map.3rsm \
      rsm_memseg_import_open_barrier.3rsm \
      rsm_memseg_import_put.3rsm \
      rsm_memseg_import_putv.3rsm \
      rsm_memseg_import_set_mode.3rsm


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
