MAN = nvlist_add_boolean.3nvpair \
      nvlist_alloc.3nvpair \
      nvlist_lookup_boolean.3nvpair \
      nvlist_lookup_nvpair.3nvpair \
      nvlist_next_nvpair.3nvpair \
      nvlist_remove.3nvpair \
      nvpair_value_byte.3nvpair


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
