INCDIR=	/usr/include/sys/dktp
INCS=	altsctr.h \
	bbh.h \
	cm.h \
	cmdev.h \
	cmdk.h \
	cmpkt.h \
	controller.h \
	dadev.h \
	dadk.h \
	dadkio.h \
	fctypes.h \
	fdisk.h \
	flowctrl.h \
	gda.h \
	quetypes.h \
	queue.h \
	tgcom.h \
	tgdk.h

.include <prog.mk>
.include <inc.mk>
