MAN = bsdmalloc.3malloc \
      malloc.3malloc \
      mapmalloc.3malloc \
      mtmalloc.3malloc \
      umem_alloc.3malloc \
      umem_cache_create.3malloc \
      umem_debug.3malloc \
      watchmalloc.3malloc


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
