MAN = ethers.3socket \
      getaddrinfo.3socket \
      getifaddrs.3socket \
      getipnodebyname.3socket \
      getnetbyname.3socket \
      getprotobyname.3socket \
      getservbyname.3socket \
      getsourcefilter.3socket \
      icmp6_filter.3socket \
      if_nametoindex.3socket \
      inet6_opt.3socket \
      inet6_rth.3socket \
      sctp_bindx.3socket \
      sctp_getladdrs.3socket \
      sctp_getpaddrs.3socket \
      sctp_opt_info.3socket \
      sctp_peeloff.3socket \
      sctp_recvmsg.3socket \
      sctp_send.3socket \
      sctp_sendmsg.3socket \
      sockaddr.3socket \
      spray.3socket


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
