MAN = ct_ctl_adopt.3contract \
      ct_dev_status_get_dev_state.3contract \
      ct_dev_tmpl_set_aset.3contract \
      ct_event_read.3contract \
      ct_pr_event_get_pid.3contract \
      ct_pr_status_get_param.3contract \
      ct_pr_tmpl_set_transfer.3contract \
      ct_status_read.3contract \
      ct_tmpl_activate.3contract


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
