INCDIR=	/usr/include/sys/scsi
INCS=	scsi.h \
	scsi_address.h \
	scsi_ctl.h \
	scsi_fm.h \
	scsi_names.h \
	scsi_params.h \
	scsi_pkt.h \
	scsi_resource.h \
	scsi_types.h \
	scsi_watch.h

SUBDIR=	adapters \
	conf \
	generic \
	impl \
	targets

.include <prog.mk>
.include <inc.mk>
