INCDIR=	/usr/include/net
INCS=	af.h \
	bridge.h \
	if.h \
	if_arp.h \
	if_dl.h \
	if_types.h \
	pfkeyv2.h \
	pfpolicy.h \
	ppp-comp.h \
	ppp_defs.h \
	pppio.h \
	radix.h \
	route.h \
	trill.h \
	vjcompress.h

.include <prog.mk>
.include <inc.mk>
