MAN = bgets.3gen \
      bufsplit.3gen \
      copylist.3gen \
      gmatch.3gen \
      isencrypt.3gen \
      mkdirp.3gen \
      p2open.3gen \
      pathfind.3gen \
      regexpr.3gen \
      strccpy.3gen \
      strfind.3gen


# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
