MAN = MP_AssignLogicalUnitToTPG.3mpapi \
      MP_CancelOverridePath.3mpapi \
      MP_CompareOIDs.3mpapi \
      MP_DeregisterForObjectPropertyChanges.3mpapi \
      MP_DeregisterForObjectVisibilityChanges.3mpapi \
      MP_DeregisterPlugin.3mpapi \
      MP_DisableAutoFailback.3mpapi \
      MP_DisableAutoProbing.3mpapi \
      MP_DisablePath.3mpapi \
      MP_EnableAutoFailback.3mpapi \
      MP_EnableAutoProbing.3mpapi \
      MP_EnablePath.3mpapi \
      MP_FreeOidList.3mpapi \
      MP_GetAssociatedPathOidList.3mpapi \
      MP_GetAssociatedPluginOid.3mpapi \
      MP_GetAssociatedTPGOidList.3mpapi \
      MP_GetDeviceProductOidList.3mpapi \
      MP_GetDeviceProductProperties.3mpapi \
      MP_GetInitiatorPortOidList.3mpapi \
      MP_GetInitiatorPortProperties.3mpapi \
      MP_GetLibraryProperties.3mpapi \
      MP_GetMPLogicalUnitProperties.3mpapi \
      MP_GetMPLuOidListFromTPG.3mpapi \
      MP_GetMultipathLus.3mpapi \
      MP_GetObjectType.3mpapi \
      MP_GetPathLogicalUnitProperties.3mpapi \
      MP_GetPluginOidList.3mpapi \
      MP_GetPluginProperties.3mpapi \
      MP_GetProprietaryLoadBalanceOidList.3mpapi \
      MP_GetProprietaryLoadBalanceProperties.3mpapi \
      MP_GetTargetPortGroupProperties.3mpapi \
      MP_GetTargetPortOidList.3mpapi \
      MP_GetTargetPortProperties.3mpapi \
      MP_RegisterForObjectPropertyChanges.3mpapi \
      MP_RegisterForObjectVisibilityChanges.3mpapi \
      MP_RegisterPlugin.3mpapi \
      MP_SetFailbackPollingRate.3mpapi \
      MP_SetLogicalUnitLoadBalanceType.3mpapi \
      MP_SetOverridePath.3mpapi \
      MP_SetPathWeight.3mpapi \
      MP_SetPluginLoadBalanceType.3mpapi \
      MP_SetProbingPollingRate.3mpapi \
      MP_SetProprietaryProperties.3mpapi \
      MP_SetTPGAccess.3mpapi \
      Sun_MP_SendScsiCmd.3mpapi

# We want to just install manpages but there is no manpage-only mk file so
# we use prog.mk.  This is ugly, but so is the entire share/man subtree.
# Eventually, it will go away and with it this hack as well.
.include <prog.mk>
