MODULE=		cpqary3
MODULE_TYPE=	drv
MODULE_DEPS=	misc/scsi
MODULE_CONF=	cpqary3.conf
SRCS=		cpqary3.c \
		cpqary3_noe.c \
		cpqary3_talk2ctlr.c \
		cpqary3_isr.c \
		cpqary3_transport.c \
		cpqary3_mem.c \
		cpqary3_scsi.c \
		cpqary3_util.c \
		cpqary3_ioctl.c \
		cpqary3_bd.c

.include <kmod.mk>
